In [1]:
import numpy as np
import random

# <u>Numpy home Exercises.</u>  


## <u>Exercises 1 :</u>

- creates a random matrix in range 10 - 99,<br>
  <u>then calculates the sum of all rows & columns .</u>

In [2]:
random_matrix = np.random.randint(10, 99, (4,3))
np_matrix_sum = 0
print(random_matrix)
for row in random_matrix:
    for rand_array_num in row:
        np_matrix_sum += rand_array_num
print(np_matrix_sum)

[[19 42 74]
 [51 84 59]
 [86 86 42]
 [73 38 79]]
733


## <u>Exercises 2 :</u>
- showing how to sum all the even elemnts in numpy array
  <br> <u>using np.sum() .</u>


In [3]:
random_array_len_10 = np.random.randint(0, 11, (10))
print(random_array_len_10)
even_num_count = np.sum(random_array_len_10 % 2 == 0)
print(even_num_count)

[ 5  7  6  5  8  6  5  9  7 10]
4


## <u>Exercises 3 :</u>
- showing how to arange, reshap, replace elemnts, <br><u>sum elements and their avarage in a numpy matrix .</u>

In [4]:
#part 1.
large_np_array = np.arange(0, 100)
print(large_np_array)

#part 2.
matrix_10x10 = large_np_array.reshape(10, 10)
print(matrix_10x10)

#part 3.
matrix_10x10[matrix_10x10 > 50] = -1
print(matrix_10x10)

#part 4.
matrix_10x10_sum = np.sum(matrix_10x10)
print(matrix_10x10_sum)

#part 5.
matrix_10x10_mean = np.mean(matrix_10x10)
print(matrix_10x10_mean)
    

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
1226
12.26


## <u>Exercises 4 :</u>
- showing how to use linspace
  <br><u>and how to take the arrays elements to make a new array with them using conditions.</u>

In [5]:
#part 1.
lin_array = np.linspace(0, 100, 10)
print(lin_array)

#part 2.
new_array = lin_array[(lin_array > 50) | (lin_array < 20)]
print(new_array)

#part 3.
reshaped_array = new_array.reshape(7, 1)
print(reshaped_array)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[  0.          11.11111111  55.55555556  66.66666667  77.77777778
  88.88888889 100.        ]
[[  0.        ]
 [ 11.11111111]
 [ 55.55555556]
 [ 66.66666667]
 [ 77.77777778]
 [ 88.88888889]
 [100.        ]]


## <u>Exercises 5 :</u>
- showing how to make np zeros matrix
  <br><u>and how to replace elements in the matrix with randomly generated numbers .</u>

- <u>i used random librarry because its more simple to generate 1 random number and choose it compared to np.random.randint() .</u>
  

In [6]:
#part 1.
np_4x4_zeros = np.zeros((4,4), dtype=int)
print(np_4x4_zeros)

#part 2.
np_4x4_zeros[0][0] = random.randint(10, 100)

np_4x4_zeros[1][3] = random.randint(10, 100)

np_4x4_zeros[-1][-1] = random.randint(10, 100)
print(np_4x4_zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[28  0  0  0]
 [ 0  0  0 20]
 [ 0  0  0  0]
 [ 0  0  0 80]]
